package genesis

import "github.com/litedag-chain/litedag-blockchain/v3/address"

// PrefundedSupply is the total balance injected at genesis outside of block rewards.
// Must equal the sum of all values in PrefundedBalances.
// When zero, genesis state comes purely from block rewards (default behavior).
//
// Generated by: go run ./cmd/snapshot-export -datadir <virel-data> -out genesis/prefunded.go
// Source: old Virel chain snapshot (1:1 balance migration, treasury excluded)
// See GENESIS_MIGRATION.md for architecture, rationale, and cleanup plan.
//
// FIXME: set to actual sum from snapshot-export tool
const PrefundedSupply uint64 = 0

// PrefundedBalances maps addresses to balances injected at genesis.
// Each address receives the specified amount in addition to any genesis block rewards.
// Addresses already receiving genesis coinbase rewards get both (additive, not overwrite).
//
// Excluded from snapshot:
//   - Old Virel treasury (v139diixrpv0ftmip4mgpuy92u51iq4pnmgjsfn) — blocked, funds burned
//   - Burn address (zero address)
//
// FIXME: populate via `go run ./cmd/snapshot-export -datadir <virel-data> -out genesis/prefunded.go`
var PrefundedBalances = map[address.Address]uint64{}
